name: pythonic_utils
description: Pythonic utils for Dart.
version: 0.1.0
homepage: https://pub.dev/packages/pythonic_utils
repository: https://github.com/VolodymyrBor/python_utils.git

environment:
  sdk: '>=2.14.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
